name: perimeterx_flutter_plugin
description: A Flutter plugin for PerimeterX integration (Android & iOS). This plugin provides a way to integrate PerimeterX security features into your Flutter app or module.
version: 1.0.3
repository: https://github.com/4rthurmonteiro/perimeterx_flutter_plugin
issue_tracker: https://github.com/4rthurmonteiro/perimeterx_flutter_plugin/issues

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pigeon: ^22.4.1


flutter:
  plugin:
    platforms:
      android:
        package: com.arthurmonteiroo.perimeterx_flutter_plugin
        pluginClass: PerimeterxFlutterPlugin
      ios:
        pluginClass: PerimeterxFlutterPlugin

topics:
  - perimeterx
  - os-integration
  - captcha
  - security

# This package supports all platforms listed below.
platforms:
  android:
  ios: