name: perimeterx_flutter_plugin
description: "A new Flutter plugin project."
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  pigeon: ^22.4.1


flutter:
  plugin:
    platforms:
      android:
        package: com.arthurmonteiroo.perimeterx_flutter_plugin
        pluginClass: PerimeterxFlutterPlugin
      ios:
        pluginClass: PerimeterxFlutterPlugin
